name: hello
on:
  workflow_dispatch:
    inputs:
      environments:
         description: "deploy env"
         default: 'staging'
         type: choice
         options:
              - staging
              - dev
jobs:
  greet:
     runs-on: ubuntu-latest
     steps:
       - name: hello to user
         run: echo "hello frnds"
       - name: hello to me
         run: echo "hello $USER"
       - name: branch name
         run: echo "${{github.ref_name}}"
       - name: print date time
         run: date "+%Y-%m-%d %H:%M:%S"
       - name: list the files
         run: ls -la
       - name: runner os
         run: uname -a
       - name: input get with
         run: echo "${{inputs.environments}}"

