name: pr check
on: 
 pull_request:
   branches:
     - master
 schedule:
   - cron: '*/5 * * * *'

jobs:
   merge_pr:
      runs-on: ubuntu-latest
      steps:
        - name: pr check
          run: echo "branch running on is ${{github.ref_name}}"
 
