name: pr check
on: 
 workflow_dispatch:
    inputs:
      environments:
         description: "deploy enr4v"
         default: 'staging'
         type: choice
         options:
              - staging
              - dev
 # schedule:
 #   - cron: '*/5 * * * *'

jobs:
   merge_pr:
      runs-on: ubuntu-latest
      steps:
        - name: pr chyteck
          run: echo "branch running on is ${{github.head_ref}}"
